### ISSUE TITLE
Header or queries parameters

### ISSUE THREAD

**Issue by Amaratsu** [CodeSpartan/UE4TcpSocketPlugin#15]
Hi, thanks for the work done.  Please add а header or queries parameters for the connection string in the form of a key and value or a map to exclude the same headers, for example: 192.168.1.100:4565?apikey=vvalvalvllvogvoa&token=hdshsbdshszgjddcb

**Comment by CodeSpartan** [comment]
TCP doesn't have any concept of query parameters.

Quoting from https://stackoverflow.com/questions/48960177/get-the-url-parameters-on-tcp-connection-stage (also read their discussion on the subject) 
> TCP doesn't have a concept of authentication during connection establishment. You'll need to decide on a protocol which will probably be used for the entire session. Once you decide on such a protocol, the client will simply send its authentication data as the first message. If the server doesn't receive valid authentication data, it will close the connection.
