### ISSUE TITLE
Connecting with my custom TCP server

### ISSUE THREAD

**Issue by rizuruu** [CodeSpartan/UE4TcpSocketPlugin#17]
Hi. I have my own custom server using Toemsel's c# library: [https://github.com/Toemsel/Network](url) 
I am connecting to it using your plugin and the connection is successful. Although I am confused about how to do data communication? Because Toemsel's library uses packet classes for it. Could you guide me to a path to follow to achieve that? I don't need a lot of complications. Just send some string/int values after the connection is established.

Thanx

**Comment by CodeSpartan** [comment]
I can't. The screenshot on the project page displays how to send data, anything above is not something I can help you with. You can ask in some discord about networking or gamedev in general.
