### ISSUE TITLE
How to listen and receive data from server？

### ISSUE THREAD

**Issue by LiXiaoRan** [CodeSpartan/UE4TcpSocketPlugin#18]
How to listen and receive data from the server？pls， Help me!!! I need to operate using a mobile devic， Can this be realized?

**Comment by CodeSpartan** [comment]
There is a screenshot that shows all the necessary information about how to use the plugin, so I'm not sure what else I can say to help you start using it. Please open issues only with specific questions.
Mobile devices are supported, as stated on the main page.

**Comment by LiXiaoRan** [comment]
ok，its client，I need WebSocket server
