### ISSUE TITLE
ConnectionId has bug?

### ISSUE THREAD

**Issue by 40kg** [CodeSpartan/UE4TcpSocketPlugin#20]
if now has 2 workers
then I do Connect
`ConnectionId = TcpWorkers.Num();`
as the code above, the new connection id will be 2
now we has 3 workers total
then I do Disconnect(1)
the total workers revert to 2 again
if I do Connect again, the new connection id will be 2 again and repeat?

**Comment by CodeSpartan** [comment]
Could you elaborate what exactly is behaving in an unexpected fashion? Because what you described seems correct.

**Comment by 40kg** [comment]
if I have 3 workers
the workersmap will be like { 0 : worker, 1 : worker, 2: worker }
then I do Disconnect(1)
the workersmap turns to { 0 : worker,  2: worker }
if I try to create a new tcpworker now, the ConnectionId generated  will repeat as 2

**Comment by CodeSpartan** [comment]
I see, thanks for the report.
