### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by DezarM** [CodeSpartan/UE4TcpSocketPlugin#25]
I use ue5.3

my errors

LogTemp: Log: Starting Tcp socket thread.
LogTemp: Log: Couldn't connect to server. TcpSocketConnection.cpp: line 411
LogTemp: Log: Tcp socket thread was destroyed.

ip 127.0.0.1
port 3457

**Comment by lsguang0** [comment]
@DezarM May I ask what is the reason for this problem? How did you solve it
