### ISSUE TITLE
 Persistent connection through level

### ISSUE THREAD

**Issue by blansikerUe4** [CodeSpartan/UE4TcpSocketPlugin#3]
Hey I asked a question on the Unreal Marketplace about persistence through level. Just in case it doesn't reach you :) 

https://www.unrealengine.com/marketplace/en-US/slug/tcp-socket-plugin/questions

**Comment by CodeSpartan** [comment]
I would try using [seamless travel (in particular, GetSeamlessTravelActorList)](https://forums.unrealengine.com/development-discussion/c-gameplay-programming/3582-keeping-actors-between-levels) if it's applicable to your project.

**Comment by blansikerUe4** [comment]
I'm using Amazon Web Services for my Servers. So I need to use Open Level in order to join a match. How hard would it be to store this directly in an UObject instead of a AActor?

Thanks you for responding!

**Comment by CodeSpartan** [comment]
You could try turning it into a UObject, but I can't guess what difficulties you may encounter, if any.

Failing that, you can always rewrite your socket server to allow temporary disconnects, and you can send your client the bulk of what messages they missed upon re-connection.

**Comment by CodeSpartan** [comment]
Saw a discussion today, that reminded me of this issue. Apparently you can add an actor to root set (AddToRoot in C++) and reference it in gameinstance, and it'll carry over into another level. https://docs.unrealengine.com/en-US/API/Runtime/CoreUObject/UObject/UObjectBaseUtility/AddToRoot/index.html
