### ISSUE TITLE
Error When Using With HoloLens Project

### ISSUE THREAD

**Issue by mh14hh** [CodeSpartan/UE4TcpSocketPlugin#8]
Receiving `Error: Missing precompiled manifest for 'TcpSocketPlugin'. This module was most likely not flagged for being included in a precompiled build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in TcpSocketPlugin.build.cs to override.` When packing with HoloLens project. The compiler suggested solution does not work.

**Comment by CodeSpartan** [comment]
Hi! Thanks, I'll try to reproduce it. Is it occurring with launcher engine
or with the engine from sources? Is the plugin in project or in engine?

вт, 16 мар. 2021 г., 17:34 mh14hh ***@***.***>:

**Comment by mh14hh** [comment]
Thanks for getting back. This issue was with the launcher/marketplace engine and it was located in the engine's plugin folder. When I pulled the TcpSocketPlugin source from git and added it into my local project's plugin folder the error went away and everything was fine. It looks like Unreal was able to rebuild it according to my project specifications for the hololens, but it did not like that I was trying to use it in the engine's plugin folder (although it worked when I packaged for windows, but not for hololens).

**Comment by CodeSpartan** [comment]
Ah. Most likely it means Epic doesn't build and doesn't ship plugins'
binaries for HoloLens. Or that I should check HoloLens support on the
marketplace page for them to try and build it. Anyway, glad it's resolved.

вт, 16 мар. 2021 г., 23:18 mh14hh ***@***.***>:

**Comment by mh14hh** [comment]
gotcha, that makes sense, thanks again!
