### ISSUE TITLE
Set SOCKET Options in Plugin

### ISSUE THREAD

**Issue by seclorum** [CodeSpartan/UE4TcpSocketPlugin#9]
Hi,

At the moment we are successfully using UE4TcpSocketPlugin for our project, but we are finding that occasionally sockets that have been disconnected 'stay around' for re-use.

There doesn't currently seem to be any way to access and set the options for a Socket provided by UE4TcpSocketPlugin - this would be useful, for example, to be able to specify SO_SOCKREUSEADDR and keep alive options, if it were exposed somehow.

**Comment by CodeSpartan** [comment]
For `SO_REUSEADDR`, simply add `Socket->SetReuseAddr();` above line 390 in TcpSocketConnection.cpp. Looks like you always need it, so it's easier to just add one line than to expose it. As far as I know, it's a very rarely needed feature. I'd accept a pull request, if it's something you're going to expose and want to contribute.

As for the keep alive options, it seems UE4 doesn't set it in engine, so there's nothing to expose, unfortunately.
If you need it, I recommend looking at how `FSocketBSD::SetReuseAddr` is implemented in `Engine\Source\Runtime\Sockets\Private\BSDSockets\SocketsBSD.cpp`. You can set `SO_KEEPALIVE` through `setsockopt` just like they're setting a bunch of options, you'll just have to modify the engine.

That being said, if you don't want to modify the engine, you can always build a fake "keep alive" mechanism on top of the existing plugin. Just send a byte from the server once a minute and send back a response byte from the client. It's far from an elegant solution, but it'd do the job.

**Comment by seclorum** [comment]
Thanks for the response - much appreciated hearing your thoughts on this issue.

Actually, we DONT always need SO_REUSEADDR - sure, for games and so on, its nice to have, since it reduces re-connection lag - but for none-game style applications, its more favourable to be able to set this option according to design, rather than assumption.  We are using TCP Socket Server in an industrial application with the UE, and would definitely need to turn this off/on according to app needs.

I will look at making a pull request, but I wanted to coordinate the feature idea with you first.
